# -*- coding: utf-8 -*-
"""chapter_08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIXxhPqKNAbq85K59GwBGmF5jBxH5wKw
"""

!pip install requests

import requests

url="https://miyashinblog.com/books/sample.html"
response=requests.get(url)
response.encoding="utf-8"
print(response.text)

!pip install beautifulsoup4

from bs4 import BeautifulSoup

soup=BeautifulSoup(response.text,"html.parser")
h1=soup.find("h1")
print(h1.text)

h2=soup.find("h2")
print(h2.text)

p=soup.find("p")
print(p.text)