# -*- coding: utf-8 -*-
"""chapter_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBHs7dyp5yEnk9Q0s2gBnZzBmNO9x6ik
"""

!pip install openai-whisper

import whisper

model=whisper.load_model("medium")

result=model.transcribe("meeting.mp4")
print(result["text"])

from getpass import getpass
google_api_key=getpass("APIキーを入力して下さい:")
print("APIキーの入力が完了しました")

from google import genai

client=genai.Client(api_key=google_api_key)

response=client.models.generate_content(
    model="gemini-2.5-flash",
    contents="Pythonでエラーが出たらGeminiに聞いても良い？簡潔に教えて",
)
print(response.text)

!pip install openai-whisper

from google.colab import files

upload_video=files.upload()

import whisper

model = whisper.load_model("medium")
result=model.transcribe("meeting.mp4")

transcribed_text = result["text"]

print(transcribed_text)

from google import genai
from getpass import getpass

google_api_key=getpass("APIキーを入力して下さい:")
client=genai.Client(api_key=google_api_key)

prompt=f"次の会議内容を簡潔に要約して下さい:{transcribed_text}"

response=client.models.generate_content(
    model="gemini-2.5-flash",
    contents=prompt,
)

print("要約結果:")
print(response.text)