# -*- coding: utf-8 -*-
"""chapter_09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13FuL2er9R9yGUzyZpOsgyfIS6Aagcbj7
"""

from sklearn import datasets

digits=datasets.load_digits()

print(digits.data.shape)

print(digits.target[:5])

print(digits.images[0])

import matplotlib.pyplot as plt

plt.imshow(digits.images[0],cmap="gray")
plt.show()

inverted_imgs=16-digits.images
plt.imshow(inverted_imgs[0],cmap="gray")
plt.show()

for i in range(10):
    plt.imshow(inverted_imgs[i],cmap="gray")
    plt.show()

import sklearn.svm

model=sklearn.svm.SVC()
model.fit(16-digits.data,digits.target)

filename="0.jpg"

from PIL import Image

image=Image.open(filename)
plt.imshow(image)
plt.show()

image=Image.open(filename)
grayscale_img=image.convert("L")
resize_img=grayscale_img.resize((8,8))
plt.imshow(resize_img,cmap="gray")
plt.show()

import numpy as np

num_img=np.asarray(resize_img,dtype=int)
print(num_img)

normalized_img=num_img*17//256
print(normalized_img)

plt.imshow(normalized_img,cmap="gray")
plt.show()

flattened_img=normalized_img.flatten()
print(flattened_img)

pred=model.predict([flattened_img])
print(pred)