# -*- coding: utf-8 -*-
"""chapter_07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4sSWG88I-CW2KxNhQys0wLrm5_SY_gY
"""

!pip install PyMuPDF

!pip install PyMuPDF
import pymupdf
doc=pymupdf.open("error.pdf")

page=doc[0]
text=page.get_text()
print(text)

doc.close()

doc=pymupdf.open("error.pdf")
doc.select([0])
doc.save("error_1page.pdf")
doc.close()

doc=pymupdf.open("error_1page.pdf")
page=doc[0]
page.set_rotation(90)
doc.save("rotated.pdf")
doc.close()

doc_a=pymupdf.open("error.pdf")
doc_b=pymupdf.open("rotated.pdf")
doc_a.insert_file(doc_b)
doc_a.save("inserted.pdf")
doc_a.close()
doc_b.close()

doc=pymupdf.open("inserted.pdf")
doc.delete_page(2)
doc.save("deleted.pdf")
doc.close()

!pip install pillow

from PIL import Image

img=Image.open("sample.jpg")

width=img.size[0]
height=img.size[1]
print(f"画像の幅は{width}")
print(f"画像の高さは{height}")

resized_width=int(width*2)
resized_height=int(height*0.5)
resized_img=img.resize((resized_width,resized_height))
resized_img.save("resized.jpg")

rotated_img=img.rotate(90)
rotated_img.save("rotated.jpg")

grayscale_img=img.convert("L")
grayscale_img.save("grayscale.jpg")