# -*- coding: utf-8 -*-
"""chapter06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pBOBtm4-KjkAs8WILbUc4byw6Le0wVqb
"""

weather="晴れ"
if weather=="晴れ":
    print("お買い物へ行きます")

weather="雨"
if weather=="晴れ":
    print("お買い物へ行きます")
elif weather=="雨":
    print("お家でゴロゴロします")

weather="曇り"
if weather=="晴れ":
    print("お買い物へ行きます")
elif weather=="雨":
    print("お家でゴロゴロします")
else:
    print("近所をお散歩します")

import random

omikuji=random.randint(0,3)
if omikuji==0:
    print("大吉")
elif omikuji==1:
    print("中吉")
else:
    print("小吉")

names=["oda","toyotomi","tokugawa"]
for name in names:
    print(name)

for i in range(5):
    print(i)

for i in range(1,10,2):
    print(i)

for i in range(1,10):
    for j in range(1,10):
        print(f"{i}×{j}={i*j}")