# -*- coding: utf-8 -*-
"""chapter05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JK8ohWlqBvNjIfHqMsRZUSM_0n8HwYMY
"""

import random

num=random.randint(1,10)
print(num)

!pip install qrcode

import qrcode
img=qrcode.make("Python楽しい!")
img.save("qrcode.png")