# -*- coding: utf-8 -*-
"""第2章_sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkE70uyd9TCQdJA57RsrcxaqfBCtwp6q
"""

print("Hello Python")

a=100
print(a)
a=150
print(a)

b="Hello Python"
print(b)
c="仙人の唐揚げ"
print(c)

print(1 + 2)
print(2 - 1)
print(1 * 2)
print(1 / 2)
print(3 // 2)
print(5 % 2)

height = 1.75
weight = 70
bmi = weight / (height * height)
print(bmi)

height = 5
width = 8

i = 123
f = 1.23
s = "ぱいせん"
b = True
print(i,f,s,b)

i = type(123)
f = type(1.23)
s = type("ぱいせん")
b = type(True)
print(i,f,s,b)

print(type(123))
print(type(True))
print(type(2.0e3))

i = "私は"
p = "Python仙人"
print(i + p)

print("私は\nPython仙人")

my_name = "私はPython仙人"
print(len(my_name))

my_name = "私はPython仙人"
print(my_name[2])

my_name = "私はPython仙人"
print(my_name[-2])

my_name = "私はPython仙人"
print(my_name[2:8])

my_name = "私はPython仙人"
print(my_name[2:])

my_name = "私はPython仙人"
print(my_name[:2])

my_name = "私はPython仙人"
print(my_name[1:8:2])

name = "ぱいせん"
message = f"Hello,{name}"
print(message)

num = 12.3
str_num = str(num)
print(str_num)
print(type(str_num))

height = 3776
print("富士山の高さは" + str(height) + "メートルです")

str_num = "123"
int_num = int(str_num)
print(int_num)
print(type(int_num))

str_num = "123.45"
float_num = float(str_num)
print(float_num)
print(type(float_num))