# -*- coding: utf-8 -*-
"""chapter-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuL7fLkUZp0Q9TA0WD0qlIL9reqqSjtr
"""

!pip install gradio

import gradio as gr

def greet(name):
    return "こんにちは、" + name + "さん!"

app = gr.Interface(fn=greet, inputs="text", outputs="text",flagging_mode="never")
app.launch()

!pip install diffusers

from diffusers import StableDiffusionPipeline
import torch

pipeline=StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4").to("cuda")
prompt="cat by picasso"
image=pipeline(prompt).images[0]

image.save(f"{prompt}.png")

!pip install gradio
!pip instrall diffusers

from diffusers import StableDiffusionPipeline
import gradio as gr
import torch

def generative_image(text):
    """
    引数で受け取ったテキストから画像を生成する関数

    引数：
    　　　text(str型)：生成したい画像を指示するテキスト
    戻り値：
    　　　image(画像データ)：生成した画像データ
    """
    pipeline=StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4").to("cuda")
    image=pipeline(text).images[0]
    return image

app=gr.Interface(
    fn=generative_image,
    inputs=gr.Textbox(label="生成したい画像の特徴を入力"),
    outputs=gr.Image(label="画像生成結果"),
    title="画像生成アプリ",
    description="テキストを入力して画像を生成します",
    flagging_mode="never",)
app.launch()